import React, { useMemo, useState, useEffect } from 'react';

const STORAGE_KEY = 'blaze-review-reflection-v1';
const pages = ['Overview','Scorecard','Reflection','Wisdom','Gap','Commitment','Recap'];
const fields = ['beingScore','leadershipScore','alignmentScore','zealScore','executionScore','beingReflection','leadershipReflection','alignmentReflection','zealReflection','executionReflection','biggestWin','hardestTruth','pattern','gap','nextStandard','commitment','proofRep','deadline'];

export default function BlazeReviewReflectionModule(){
  const [page,setPage]=useState('Overview');
  const [data,setData]=useState(()=>{try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}catch{return {}}});
  useEffect(()=>{localStorage.setItem(STORAGE_KEY,JSON.stringify(data))},[data]);
  const update=(k,v)=>setData(d=>({...d,[k]:v}));
  const progress=useMemo(()=>Math.round(fields.filter(k=>String(data[k]||'').length>0).length/fields.length*100),[data]);
  const input=(k,label,type='textarea')=>(<div className="field"><label>{label}</label>{type==='input'?<input value={data[k]||''} onChange={e=>update(k,e.target.value)} placeholder="Type here..."/>:<textarea value={data[k]||''} onChange={e=>update(k,e.target.value)} placeholder="Type here..."/>}</div>);
  const score=(k,label)=>(<div className="score"><h4>{label}</h4><input type="range" min="1" max="10" value={data[k]||5} onChange={e=>update(k,e.target.value)}/><b>{data[k]||5}/10</b></div>);
  const recap=`B.L.A.Z.E. REVIEW + REFLECTION\n\nScores:\nBeing: ${data.beingScore||5}/10\nLeadership: ${data.leadershipScore||5}/10\nAlignment: ${data.alignmentScore||5}/10\nZeal: ${data.zealScore||5}/10\nExecution: ${data.executionScore||5}/10\n\nBiggest Win:\n${data.biggestWin||''}\n\nHardest Truth:\n${data.hardestTruth||''}\n\nPattern:\n${data.pattern||''}\n\nBiggest Gap:\n${data.gap||''}\n\nNew Standard:\n${data.nextStandard||''}\n\nNext Commitment:\n${data.commitment||''}\n\nProof Rep:\n${data.proofRep||''}\n\nDeadline:\n${data.deadline||''}\n\nIf pressure hits, then I will:\n${data.ifThen||''}`;

  return <div className="blazeReview">
    <style>{css}</style>
    <section className="hero"><div className="kicker">B.L.A.Z.E. Integration Chamber</div><h1>Review + Reflection</h1><p>This is where the training becomes wisdom. Review the five pillars, score the evidence, extract the lesson, and create the next commitment.</p></section>
    <div className="layout"><aside><small>Progress</small><div className="bar"><span style={{width:`${progress}%`}}/></div><b>{progress}% complete</b>{pages.map(p=><button key={p} className={page===p?'active':''} onClick={()=>setPage(p)}>{p}</button>)}<button onClick={()=>setData({})}>Reset</button></aside>
    <main>
      {page==='Overview'&&<section className="card"><h2>The Point of the Review</h2><p>B.L.A.Z.E. is not meant to stay as a concept. The review makes the system practical. You ask: Where did I become stronger? Where did I react? What evidence do I have? What is the next standard?</p><div className="letters">{['Being','Leadership','Alignment','Zeal','Execution'].map((x,i)=><div><b>{'BLAZE'[i]}</b><span>{x}</span></div>)}</div><div className="proof">Do not judge yourself. Study yourself. A boss uses truth to make the next move cleaner.</div></section>}
      {page==='Scorecard'&&<section className="card"><h2>B.L.A.Z.E. Scorecard</h2><p>Score each pillar honestly from 1–10. The number tells you where the next breakthrough lives.</p><div className="scores">{score('beingScore','Being')}{score('leadershipScore','Leadership')}{score('alignmentScore','Alignment')}{score('zealScore','Zeal')}{score('executionScore','Execution')}</div></section>}
      {page==='Reflection'&&<section className="card"><h2>Pillar Reflection</h2>{input('beingReflection','B — Being: Who did I choose to be, and where did I fall back into the old identity?')}{input('leadershipReflection','L — Leadership: Where did I lead myself well, and where did I react?')}{input('alignmentReflection','A — Alignment: Where did my actions match my values, and where did they split?')}{input('zealReflection','Z — Zeal: Where did I bring real fire, and where was it hype or panic?')}{input('executionReflection','E — Execution: What did I actually complete, prove, or move forward?')}</section>}
      {page==='Wisdom'&&<section className="card"><h2>Extract The Wisdom</h2>{input('biggestWin','Biggest win: what worked and why?')}{input('hardestTruth','Hardest truth: what did I not want to admit?')}{input('pattern','Pattern: what keeps showing up across the five pillars?')}{input('lesson','Lesson: what sentence do I need to remember next time pressure hits?')}</section>}
      {page==='Gap'&&<section className="card"><h2>Find The Gap</h2>{input('gap','What is the biggest B.L.A.Z.E. gap right now?')}{input('cost','What will this gap cost me if I keep ignoring it?')}{input('nextStandard','What is the new standard that closes the gap?')}</section>}
      {page==='Commitment'&&<section className="card"><h2>Next B.L.A.Z.E. Commitment</h2>{input('commitment','My next B.L.A.Z.E. commitment is...')}{input('proofRep','The proof rep I will complete is...')}{input('deadline','Deadline / when I will do it','input')}{input('ifThen','If pressure hits, then I will...')}</section>}
      {page==='Recap'&&<section className="card"><h2>Final Lock-In</h2><pre>{recap}</pre><button className="primary" onClick={()=>navigator.clipboard.writeText(recap)}>Copy Recap</button></section>}
    </main></div>
  </div>
}

const css = `
.blazeReview{min-height:100vh;background:radial-gradient(circle at top left,rgba(209,30,255,.24),transparent 35%),#030006;color:#f8ecff;padding:28px;font-family:Inter,system-ui}.hero,.card,aside{border:1px solid rgba(255,255,255,.11);background:rgba(9,0,18,.82);border-radius:26px;padding:24px;box-shadow:0 0 34px rgba(209,30,255,.14)}.hero h1{font-size:clamp(42px,7vw,82px);margin:8px 0;background:linear-gradient(90deg,#ff3edb,#d11eff,#00f0ff,#00ffbf);-webkit-background-clip:text;color:transparent}.hero p,p{color:#bda8c9;line-height:1.6}.kicker{color:#00f0ff;letter-spacing:.18em;text-transform:uppercase;font-weight:900}.layout{display:grid;grid-template-columns:280px 1fr;gap:18px;margin-top:18px}aside{height:max-content;position:sticky;top:18px}aside button{display:block;width:100%;margin:8px 0;padding:13px;border-radius:16px;border:1px solid rgba(255,255,255,.11);background:rgba(255,255,255,.04);color:#f8ecff;font-weight:900;text-align:left;cursor:pointer}aside button.active{border-color:#00f0ff;box-shadow:0 0 18px rgba(0,240,255,.18)}.bar{height:12px;border-radius:999px;background:rgba(255,255,255,.08);overflow:hidden;margin:10px 0}.bar span{display:block;height:100%;background:linear-gradient(90deg,#ff3edb,#d11eff,#00f0ff)}.letters,.scores{display:grid;grid-template-columns:repeat(5,1fr);gap:10px}.letters div,.score{border:1px solid rgba(255,255,255,.11);background:#05000a;border-radius:18px;padding:14px}.letters b{display:block;font-size:36px;background:linear-gradient(90deg,#ff3edb,#00f0ff);-webkit-background-clip:text;color:transparent}.letters span{font-weight:900}.proof{border-left:4px solid #00ffbf;background:rgba(0,255,191,.07);border-radius:14px;padding:14px;margin-top:14px}.field{margin:14px 0}.field label{display:block;font-weight:900;margin-bottom:7px}.field textarea,.field input{width:100%;background:#05000a;border:1px solid rgba(255,255,255,.14);border-radius:16px;color:#f8ecff;padding:13px;font:inherit}.field textarea{min-height:95px}pre{white-space:pre-wrap;background:#030006;border:1px solid rgba(0,240,255,.24);border-radius:18px;padding:16px}.primary{border:0;background:linear-gradient(90deg,#00f0ff,#00ffbf);color:#020206;border-radius:16px;padding:13px 16px;font-weight:1000}@media(max-width:900px){.layout,.letters,.scores{grid-template-columns:1fr}aside{position:relative;top:auto}}`;
